function Hd = zuixiaoerchengHighpass
%ZUIXIAOERCHENGHIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 01-Apr-2023 09:57:13

% FIR least-squares Highpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

N     = 1000;  % Order
Fstop = 0.1;   % Stopband Frequency
Fpass = 0.6;   % Passband Frequency
Wstop = 1;     % Stopband Weight
Wpass = 1;     % Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass]);
Hd = dfilt.dffir(b);

% [EOF]
